# Generated by Django 5.0.6 on 2024-05-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "approved"),
                    ("PENDING", "pending"),
                    ("UNDER DISCUSSION", "under discussion"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
