# Generated by Django 5.0.6 on 2024-05-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_propertylisting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="address",
            field=models.CharField(
                blank=True, default="X-Y-Z", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
