# Generated by Django 5.0.6 on 2024-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_propertycomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "approved"),
                    ("PENDING", "pending"),
                    ("UNDER DISCUSSION", "under discussion"),
                    ("REJECTED", "REJECT"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
