# Generated by Django 5.0.6 on 2024-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
