# Generated by Django 5.0.6 on 2024-05-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_notification_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="attended",
            field=models.BooleanField(default=False),
        ),
    ]
